orbs:
  node: circleci/node@3.0.0
  discord: teka23/discord@0.0.1

version: 2.1

executors:
  node-cointainer:
    docker:
      - image: circleci/node

jobs:
  test:
    executor: node-cointainer
    steps:
      - run: npm run test
      - discord/approval-notification:
          message: Pending approval
          webhook: webhook

workflows:
  "Test API":
    jobs:
      - test
