jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
      # - discord/status:
      #     mentions: "USERID1,USERID2,&ROLE_ID1,here,everyone"
      #     only_for_branches: master
      #     webhook: webhook

orbs:
  node: circleci/node@3.0.0
  discord: teka23/discord@0.0.1
version: 2.1

workflows:
  "Test API":
    jobs:
      - test
