orbs:
  node: circleci/node@3.0.0
  discord: teka23/discord@0.0.1

version: 2.1

jobs:
  install-node-example:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version

  test:
    executor: node-cointainer
    steps:
      - run: npm run test
      # - discord/status:
      #     mentions: "USERID1,USERID2,&ROLE_ID1,here,everyone"
      #     only_for_branches: master
      #     webhook: webhook

workflows:
  "Test API":
    jobs:
      - install-node-example
