jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test

      - discord/status:
          failure_message: ":face_with_symbols_over_mouth: $CIRCLE_USERNAME Seu estúpido! Você quebrou o projeto na branch $CIRCLE_BRANCH. Pipeline: $CIRCLE_JOB"
          success_message: "Pipeline rodado com sucesso"
          webhook: https://discordapp.com/api/webhooks/758836655007465552/Km8D68GqmqB17SCDfp_PbayMUNXRWgy-0tcJg4xl8s8fIgL4_IIZJBlWqI8BqjMwuE-L

orbs:
  node: circleci/node@3.0.0
  discord: teka23/discord@0.0.1
version: 2.1

workflows:
  "Test API":
    jobs:
      - test
